### ISSUE TITLE
Does not enclose the whole bracket to iTerm using cmd+return in Mac + R script.

### ISSUE THREAD

**Issue by jintaili** [randy3k/SendCode#125]
Hi! Up to several days ago, when running Sublime Text + iTerm on an R script with nesting brackets, pressing cmd+return at a line including an opening bracket would send code up to the corresponding enclosing bracket to iTerm. However, recently, this behaviour has changed, it is not clear what would be sent to iTerm but it seems to be usually up until the first enclosing bracket to iTerm. For example:
```
mysummary <- function(x,npar=TRUE,print=TRUE) {
  if (!npar) {
    center <- mean(x); spread <- sd(x)
  } else {
    center <- median(x); spread <- mad(x)
  }
  if (print & !npar) {
    cat("Mean=", center, "\n", "SD=", spread, "\n")
  } else if (print & npar) {
    cat("Median=", center, "\n", "MAD=", spread, "\n")
  }
  result <- list(center=center,spread=spread)
  return(result)
}
```

Previously, putting my cursor at the first line, the whole function would be sent to iTerm. Recently, only the first three lines are.

SendCode (OSX).sublime-settings:
```
{
    "prog": "terminal",
    "auto_expand_line": true,
    "auto_advance" : true,
    "auto_advance_non_empty": false,
    "bracketed_paste_mode": false,
    "block_start_pattern": "# ?%%|# ?\\+|# In \\[",
    "block_end_pattern": "# ?%%|# ?\\+|#'|# In \\[",

    "r" : {
        "prog": "terminal",
        // turn brackted paste mode on if radian or readline 7.0 is used
        "bracketed_paste_mode": false
    },

    "rmd" : {
        "prog": "terminal",
        // turn brackted paste mode on if radian or readline 7.0 is used
        "bracketed_paste_mode": false
    },

    "python" : {
        "prog": "terminal",
        "bracketed_paste_mode": true
    },

    "julia" : {
        "prog": "terminal",
        "bracketed_paste_mode": true
    }

    // path related settings

    // path to tmux
    // "tmux": "tmux",

    // path to screen
    // "screen": "screen"
}
```
SendCode.sublime-settings:
```
{
	"prog": "iterm",
	"r":
	{
		"bracketed_paste_mode": false,
		"prog": "iterm"
	}
}
```

**Comment by randy3k** [comment]
I cannot reproduce it. The whole block would be sent if the cursor is placed on the first line.

**Comment by randy3k** [comment]
Oh, I could reproduce it now build 3210.

**Comment by randy3k** [comment]
59db870 should fix it.

**Comment by randy3k** [comment]
`v0.4.19` has released and it should fix the issue.

**Comment by jintaili** [comment]
Thanks! I tried upgrading using Package Control and restarting Sublime Text, but that did not seem to resolve the issue. Am I missing something? (Relatively new to git) Thanks!

**Comment by randy3k** [comment]
Could you check what version of SendCode you have installed?

**Comment by jintaili** [comment]
Yes it is 0.4.19. And I checked the source getter.py and it seemed [59db870](https://github.com/randy3k/SendCode/commit/59db870e53013f6b504ea1f22edc626688062d5e) has been applied. Still behaves weirdly with R.

**Comment by randy3k** [comment]
Did you restart Sublime Text? And what version do you have?

**Comment by jintaili** [comment]
Yes I did. My Sublime is 3.2.2, build 3211.

**Comment by randy3k** [comment]
Oic, it seems that I need to bump up the build check by one more build to 3211.

**Comment by jintaili** [comment]
Thanks! Please let me know if progress has been made or if you need my help.

**Comment by randy3k** [comment]
The latest release should fix it.

**Comment by jintaili** [comment]
Thank you! It seems to be working now.
