### ISSUE TITLE
Sending code to RStudio doesn't evaluate code (also Ctrl is stuck on)

### ISSUE THREAD

**Issue by TimothyHyndman** [randy3k/SendCode#37]
Running Windows 10 with R 3.4.0, RStudio 1.0.143, Sublime Text Build 3126, and R-box. When I send code from sublime to RStudio with Ctrl+Enter, the code is copied but not evaluated in RStudio. Also, the computer acts as if Ctrl is held down from when I send the code until I press Ctrl again.

Currently I have to go into RStudio and press Ctrl then Enter to evaluate the code.

**Comment by randy3k** [comment]
What version of SendCode are you using? The support for RStudio on Windows has been improved two weeks ago (v0.2.3). I expect that the update should fix the issue that you have reported. Please let me know if you using the most recent version.

**Comment by TimothyHyndman** [comment]
I'm using v0.2.3, I installed it today.

**Comment by randy3k** [comment]
Can you try the following two tasks and report to here?

1. Do `Ctrl+enter` but release Ctrl almost immediately.

2. Do `Ctrl+enter` but hold Ctrl for additional 2 seconds.

**Comment by TimothyHyndman** [comment]
Both 1 and 2 give me the same result as before

**Comment by randy3k** [comment]
I cannot reproduce it in my windows 8 virtual machine. May need a PC to investigate it.

**Comment by TimothyHyndman** [comment]
Okay. I am running windows 10 btw, so may be different in 8.

**Comment by randy3k** [comment]
It is strange, I expected that (2) should always work.

**Comment by randy3k** [comment]
I installed a windows 10 virtual machine and reproduced the same issue.

**Comment by randy3k** [comment]
v0.2.4 should fix it. Let me know if it doesn't.

**Comment by TimothyHyndman** [comment]
Okay, I updated to v0.2.4 but I'm getting the same issue. 1 and 2 still don't work. BTW, I get this issue regardless of whether my computer is busy or not.

**Comment by randy3k** [comment]
BTW, are you using a 32bit / 64 bit windows? How about Sublime Text, 32 or 64?

**Comment by randy3k** [comment]
I updated again the delay settings. You can also tweak [this](https://github.com/randy3k/SendCode/blob/fb7c49d0ffffb3e355ac3060b933129c0b04fabe/src/rstudio/__init__.py#L36) line to try different delay time. The issue is probably due to the different timing. Setting this too short may result in not sending the "Enter" key and on the other hand, setting it too long may cause the "Ctrl" key sticky.

**Comment by TimothyHyndman** [comment]
I'm using 64bit Windows and 64bit Sublime. Enter key is now being sent and is working although I still had the sticky control problem. I've sent a pull request for an update to fix the sticky control key. I'm very new to git so I hope I've done it right.

BTW, it seems that the main problem is that RStudio won't run a line of code with Ctrl-Enter, it only accepts Enter by itself. So for now, if I don't hold onto Ctrl for too long it works fine, but if I keep it held down, the code doesn't run in RStudio.

**Comment by randy3k** [comment]
Unfortunately, your fix doesn't allow sending Ctrl+Enter multiple times without leaving the Ctrl key.

**Comment by TimothyHyndman** [comment]
Ah, okay, sorry. RStudio won't run any code at all for me if Ctrl is held down so I didn't realise that was intended behaviour. 

Adding win32api.keybd_event(win32con.VK_CONTROL, 0, win32con.KEYEVENTF_KEYUP, 0) at line 40 also fixed the sticky control for me but I don't know if that stuffs up being able to hold Ctrl down since I can't test that.

**Comment by rrodrigueznt** [comment]
Hi! I'm seeing a similar behaviour here working with Windows 7 Professional. R 3.4.0, RStudio 1.0.143, Sublime Text Build 3126, R-box v.3.4.8 and SendCode v0.2.4. But it doesn't happen always. I would say that only from time to time and if I start Sublime Text first, then, RStudio. Please, does this any sense for you? Thanks!

**Comment by randy3k** [comment]
The support of RStudio on Windows is a kind of hack. This cannot be perfectly solved unless RStudio adds a API for sending code or fixes https://support.rstudio.com/hc/en-us/community/posts/208160308-ctrl-enter-doesn-t-work-in-R-console-without-a-source-file-opened-.

**Comment by rrodrigueznt** [comment]
Thanks, Randy! Added +1 and following RStudio issue! I'm afraid it is taking a bit longer to fix it!

**Comment by aeonstone** [comment]
I am having a similar issue but the fix for me seems to be that I have to hold the enter key down for several seconds. This causes other issues though because sublime text starts jumping to the following lines and then SendCode will start sending the next lines of code to RStudio.

I am also getting some bad interactions between SendCode and AutoHotKey. I saw you were able to fix some of these issues with SendText+, any chance those fixes will show up here? To be specific, I remapped Ctrl and Capslock. When I hit Ctrl+Enter (actually Capslock + Enter) Sendcode sends the code to RStudio but it is also toggling my Capslock. I don't run into this behavior anywhere else in Sublime Text.

Thanks for all the work!

Jared

**Comment by randy3k** [comment]
Believe me, I have spent so much time to hack RStudio on Windows. What I want to accomplish is a way to send code to RStudio without changing focus.

The issue of AutoHotKey and here is exactly the same. To be more specific, when `Ctrl+enter` is hit, we need to "release" the control key and electronically send an "enter" keystroke to RStudio. After this, we need to "re-press" the `Ctrl` key.  However, there is no way Windows knows if a key is physically pressed if the state of key has been modified by Windows. The current implementation of such behavior is hacky, hence leads to all the reports here.

There are two ugly solutions here.

1. switching the focus of the current sublime window to RStudio, send the code, switch back to RStudio. I consider this is a ugly solution because it is annoying

2. we need to make sure an empty R script file is opened. It is an solution used by SendText+.
we need that empty R script file because of a RStudio bug: https://support.rstudio.com/hc/en-us/community/posts/208160308-ctrl-enter-doesn-t-work-in-R-console-without-a-source-file-opened-

I suggest we should roll back to the solution 2, maybe.

**Comment by randy3k** [comment]
v0.2.6 switches back to the old solution used in SendText+, hope it will alleviate some of the pains here.

**Comment by aeonstone** [comment]
Just this morning I found a way to solve my issue. Based on what you said I did some more reading about how AutoHotKey worked. From what I understood the issue was simply that AHK runs "on top of" windows so there was some weird interactions between AHK, Sublime, SendCode, and ultimately RStudio. 

The answer it seemed to me was to just swap the keys at a lower level. I found that Sharpkeys (https://github.com/randyrants/sharpkeys) can remap the keys at the registry level. The seems to have solved the problem because the remapping happens at a lower level. All of my problems have been resolved. You might want to recommend this people if this issue comes up in the future, or maybe include it in a FAQ. 

Thanks for all the great work. I really love what you've done with this project!
