### ISSUE TITLE
holding ctrl will not send repeated lines of code

### ISSUE THREAD

**Issue by bitworm** [randy3k/SendCode#97]
On macos, I could hold down the meta key and press enter successive times to send multiple lines of code. 

On Ubuntu 14.04, if I hold `ctrl`  and press `return` repeatedly, it will send the first line but insert a new line in ST3 on successive presses, as though sendcode didn't get the `ctrl` command.

Any ideas?

Thank you

**Comment by randy3k** [comment]
which program are you sending to?

**Comment by bitworm** [comment]
Terminal (ubuntu 14.0)

**Comment by randy3k** [comment]
So I assume you are talking about gnome-terminal, or is it?

**Comment by bitworm** [comment]
Unity(?) whatever ships as default.

**Comment by randy3k** [comment]
Ya, I could reproduce it the ctrl thing. It is unfortunate a shortcoming of sending code to linux terminals. Send code to gnome terminal is based on a "hack" so a lot of things may not work as expected. My recommendation is to use tmux on linux.

Terminus has been quite stable currently, though I am not surprised that it is still bugged.

**Comment by bitworm** [comment]
I have now tested with tmux and still have the same issue.  Do you have any suggestions for debugging this issue?

**Comment by randy3k** [comment]
I don't expect tmux has the issue. Could you confirm that the `prog` is set as `tmux`?

**Comment by bitworm** [comment]
oh yea!  Working now.  I guess I'll leave this open, as the issue was unresolved?  A sendcode-like REPL environment is so core to my workflow, I'll switch to tmux.  Thanks.

**Comment by emilBeBri** [comment]
is there a linux terminal that does not have this issue? Does anybody know that? Tmux works smoothly in this regard, it has two drawbacks however, that is resolved when using a terminal directly:

1) the colors change - so when using rtichoke the colors doesn't have a very good look
2) scrolling with the mouse is disabled

**Comment by randy3k** [comment]
It is, unfortunately, an common issue shared by any linux terminal which depends on xdotool. We may have a better luck with temrinals which support dbus. Konsole is the only one which I know of supporting dbus and I didn't have time to look into that.

**Comment by maxfarrell** [comment]
Hi I'm experiencing the same problem, but then I set tmux as the SendCode program, I'm still having the same issue (using tmux within gnome-terminal).

I'm using Sublime version 3.2.2 build 3211
